import {
  LAYOUT_MOBILE_BREAKPOINT,
  LAYOUT_SMALL_BREAKPOINT,
  LAYOUT_SIDEBAR_WIDTH_PX,
  LAYOUT_GRID_MIN_COL_WIDTH_PX,
  LAYOUT_ROW_HEIGHT_DESKTOP,
  LAYOUT_ROW_HEIGHT_MOBILE,
  LAYOUT_VIRTUAL_BUFFER_ROWS,
} from '@mspr/shared';

export {
  LAYOUT_MOBILE_BREAKPOINT,
  LAYOUT_SMALL_BREAKPOINT,
  LAYOUT_SIDEBAR_WIDTH_PX,
  LAYOUT_GRID_MIN_COL_WIDTH_PX,
  LAYOUT_ROW_HEIGHT_DESKTOP,
  LAYOUT_ROW_HEIGHT_MOBILE,
  LAYOUT_VIRTUAL_BUFFER_ROWS,
};

export const MOBILE_HEADER_HEIGHT = 52;
export const SEARCH_HEADER_HEIGHT = 64;
export const SIDEBAR_PADDING_X = 16;
export const SIDEBAR_PADDING_Y = 24;
export const SCROLL_AREA_PADDING_DESKTOP = 24;
export const SCROLL_AREA_PADDING_MOBILE = 12;
export const MEDIA_GRID_GAP_DESKTOP = 20;
export const MEDIA_GRID_GAP_MOBILE = 10;
export const MEDIA_GRID_GAP_SMALL = 8;

export const Z_INDEX = {
  MOBILE_HEADER: 100,
  DRAWER_OVERLAY: 200,
  PLAYER_OVERLAY: 1000,
  VIEWER_OVERLAY: 1000,
  VIEWER_HEADER: 1001,
  VIEWER_NAV_ARROW: 1001,
  VIEWER_SCALE_INDICATOR: 1001,
};
