import {
  PLAYER_PROGRESS_SAVE_INTERVAL_MS,
  PLAYER_RESUME_THRESHOLD_SECONDS,
  PLAYER_SEEK_KEYBOARD_STEP_SECONDS,
  PLAYER_VOLUME_STEP,
  PLAYER_VOLUME_MIN,
  PLAYER_VOLUME_MAX,
} from '@mspr/shared';

export {
  PLAYER_PROGRESS_SAVE_INTERVAL_MS,
  PLAYER_RESUME_THRESHOLD_SECONDS,
  PLAYER_SEEK_KEYBOARD_STEP_SECONDS,
  PLAYER_VOLUME_STEP,
  PLAYER_VOLUME_MIN,
  PLAYER_VOLUME_MAX,
};

export const PROGRESS_TRACK_HEIGHT = 5;
export const PROGRESS_TRACK_RADIUS = 3;
export const PLAY_BTN_SIZE = 60;
export const PLAY_BTN_SIZE_MOBILE = 52;
export const VOLUME_SLIDER_WIDTH = 90;
export const VOLUME_SLIDER_HEIGHT = 4;
export const COVER_MAX_WIDTH = 300;
export const COVER_MAX_WIDTH_MOBILE = 220;
export const AUDIO_CONTROLS_MAX_WIDTH = 420;
